name: PR Reminders

on:
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  reminders:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Reminders Summary
      run: |
        BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        case "$BRANCH_NAME" in
          bug/*)
            TAG="bug"
            ;;
          feature/*)
            TAG="feature"
            ;;
          test/*)
            TAG="test"
            ;;
          *)
            TAG="none"
            ;;
        esac
        echo '### 🔔 Reminders:' >> $GITHUB_STEP_SUMMARY
        echo '1. Ensure your pull request branch is up to date with main.' >> $GITHUB_STEP_SUMMARY
        echo '2. Assign a reviewer to your pull request.' >> $GITHUB_STEP_SUMMARY
        echo '3. Assign the suggested tag: **'$TAG'** to your pull request.' >> $GITHUB_STEP_SUMMARY
        echo '4. Branch name: **'$BRANCH_NAME'**' >> $GITHUB_STEP_SUMMARY

    - name: Post Reminders Summary as PR Comment
      run: |
        COMMENT_BODY="### 🔔 Reminders:\n"
        COMMENT_BODY+="1. Ensure your pull request branch is up to date with main.\n"
        COMMENT_BODY+="2. Assign a reviewer to your pull request.\n"
        COMMENT_BODY+="3. Assign the suggested tag: **$TAG** to your pull request.\n"
        COMMENT_BODY+="4. Branch name: **$BRANCH_NAME**"
        echo "$COMMENT_BODY" > comment.txt
        curl -v \
          -X POST \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"body\": \"$(cat comment.txt)\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
